### ISSUE TITLE
Code for visualization of the feature map activation

### ISSUE THREAD

**Issue by CaelynCheung1996** [josedolz/LiviaNET#13]
Hi Jose,

I am quite curious about the figures you showed about the feature map activation. I want to implement that too. Do you have that part of code available or any idea how I can add on it. Thanks.

**Comment by josedolz** [comment]
Hi @CaelynCheung1996 

I'll try to upload a piece of code showing how this can be done. Basically you need to access to the output of each layer (i.e. feature map) and save it in the format you prefer.

Jose

**Comment by CaelynCheung1996** [comment]
Thanks Jose. I will greatly appreciate if you can show me that part of code (new starters of theano...).

**Comment by josedolz** [comment]
Hi @CaelynCheung1996 

sorry for the delay. I am quite busy and do not find time to manage all these small issues/questions.

To get the feature maps, for example when you want to segment the model (since the model would be ideally trained), you can do the following (in startTesting.py):

from line 120:

```
predictions = myNetworkModel.networkModel_Test(0)'
```
Choose from which layer you want to get the feature maps.
```
featMaps = predictions[layer]
```

Then you can save it in matlab format as:
```
nameToSave = 'xxxxxxx.mat'
scipy.io.savemat(nameToSave,mdict={'Fm':featMaps})
```

Hope it helps.

**Comment by CaelynCheung1996** [comment]
Thanks so much for the guide!
